spring:
  application:
    name: MeuSiteBackend
  r2dbc:
    url: r2dbc:pool:postgresql://postgres:postgres@localhost:5432/meu_site
    password: remoto
    username: 438537
  webflux:
    base-path: /meu-site-backend
server:
  port: 8080
